// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmFMFoAR8taiBIF6swviX2hb0_9z5dfNE',
    appId: '1:283238161604:web:3573334225551974f5fd91',
    messagingSenderId: '283238161604',
    projectId: 'hearyourhome-92092',
    authDomain: 'hearyourhome-92092.firebaseapp.com',
    storageBucket: 'hearyourhome-92092.appspot.com',
    measurementId: 'G-PX8BYKXY65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6N4EkShCqHUT8vjR1jLInv4ghCapOM6I',
    appId: '1:283238161604:android:26806f72498683a0f5fd91',
    messagingSenderId: '283238161604',
    projectId: 'hearyourhome-92092',
    storageBucket: 'hearyourhome-92092.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNDBIrgDoIx9cGqcbT4NAgJTa7hcA4PwQ',
    appId: '1:283238161604:ios:39c8a777aa3347dff5fd91',
    messagingSenderId: '283238161604',
    projectId: 'hearyourhome-92092',
    storageBucket: 'hearyourhome-92092.appspot.com',
    iosClientId: '283238161604-56gic9oqqaph7knkomv27h3ftpahrkmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
